/// Flutter icons Pedometer
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pedometer
///      fonts:
///       - asset: fonts/Pedometer.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Pedometer {
  Pedometer._();

  static const _kFontFam = 'Pedometer';

  static const IconData fire = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData footsteps_silhouette_variant =
      const IconData(0xe802, fontFamily: _kFontFam);
}
